lassallemuseu/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls', namespace="index")),
    path('artifacts/', include("artifacts.urls", namespace="artifacts")),
    path('pdv/', include("pdv.urls", namespace="pdv")),
    path('collection/', include("collection.urls", namespace="collection")),
    path('materials/', include("materials.urls", namespace="materials")),
    path('aboutus/', include("aboutus.urls", namespace="aboutus")),
    path('contact/', include("contact.urls")),
    path('tinymce/', include('tinymce.urls')),
    path('products/', include("products.urls", namespace="products")),
]

if settings.DEBUG:  # new
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

materials/urls.py
from django.urls import path

from . import views

app_name = "materials"

urlpatterns = [
    path("", views.MaterialsListView.as_view(), name="list"),
    path("<slug:slug>/", views.MaterialsDetailView.as_view(), name="detail")
]

pdv/urls.py
from django.urls import path, re_path

from . import views

app_name = "pdv"

urlpatterns = [
    re_path(r'pdv/add/$',  views.PDVCreateView.as_view(),
            name='pdv_add'),
    path('', views.index_pdv),
    path('caixa/', views.frente_caixa, name='caixa'),
    path('caixa/itens-cupom/', views.itens_cupom, name='itens-cupom'),
]

artifacts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from tinymce.models import HTMLField
from ckeditor.fields import RichTextField
import string, random
from django.urls import reverse_lazy

# def generateId():
#     length = 12

    # while True:
    #     artifact_id = ''.join(random.choices(string.ascii_uppercase, k=length))
    #     if Artifacts.objects.filter(artifact_id=artifact_id).count() == 0:
    #         break
    # return artifact_idfrom django.core.urlresolvers import reverse

class Artifacts(models.Model):
    #artifact_id = models.CharField(max_length=30, default="", unique=True, primary_key=True) #No de registro
    name = models.CharField(max_length=50, default="", unique=False)
    slug = models.SlugField(max_length=50, default="", unique=True)
    description = models.CharField(max_length=200, default="", unique=False)
    author = models.CharField(max_length=50, default="Desconhecido", unique=False)
    about = RichTextField(blank=True)
    usage = models.CharField(max_length=60, default="Desconhecido", unique=False)
    style = models.CharField(max_length=30, default="Desconhecido", unique=False)
    culture = models.CharField(max_length=30, default="Desconhecida", unique=False)
    ethnicity = models.CharField(max_length=30, default="Desconhecida", unique=False)
    age = models.CharField(max_length=12, default="Desconhecido", unique=False)
    inscriptions = models.CharField(max_length=200, default="Desconhecido")
    fabrication_date = models.CharField(max_length=12, default="Desconhecido", unique=False)
    heritage_id = models.CharField(max_length=30, default="", unique=True) #No de livro tombo
    manufacture = models.CharField(max_length=30, default="Desconhecida", unique=False)
    decoration = models.CharField(max_length=30, default="Desconhecida", unique=False)
    collection = models.ForeignKey('collection.collection', default="", related_name='collection', on_delete=models.CASCADE)
    material = models.ForeignKey('materials.materials', default="",related_name='material', on_delete=models.CASCADE)
    length = models.FloatField(max_length=5, default=0)
    width = models.FloatField(max_length=5, default=0)
    diameter = models.FloatField(max_length=5, default=0)
    height = models.FloatField(max_length=5, default=0)
    circumference = models.FloatField(max_length=5, default=0)
    depth = models.FloatField(max_length=5, default=0)
    weight = models.FloatField(max_length=5, default=0)
    owner = models.CharField(max_length=30, default="Desconhecido", unique=False)
    acqusition_date = models.CharField(max_length=12, default="Desconhecido", unique=False)
    donor = models.CharField(max_length=30, default="Desconhecido", unique=False)
    last_owner = models.CharField(max_length=30, default="Desconhecido", unique=False)
    personality = models.CharField(max_length=30, default="Desconhecido", unique=False)
    post_author = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images/', height_field=None, width_field=None, max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    
   
    
    class Meta:
        ordering = ("-created",)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("artifacts:detail", kwargs={"slug": self.slug})
    

   
    def get_main_edit(self):
        return reverse("artifacts:artifacts-update", kwargs={"pk": self.id})

materials/models.py
from django.db import models
from ckeditor.fields import RichTextField
import string

class Materials(models.Model):
    #material_id = models.CharField(max_length=30, unique=True, primary_key=True) #No de registro
    name = models.CharField(max_length=30, default="Desconhecido", unique=True)
    slug = models.SlugField(max_length=50, default="", unique=True)
    description = RichTextField(blank=True)
    image = models.ImageField(upload_to='images/', height_field=None, width_field=None, max_length=100, default=0)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("artifacts:detail", kwargs={"slug": self.slug})

materials/views.py
from django.views.generic import DetailView, ListView

from .models import Materials

class MaterialsListView(ListView):
    model = Materials

class MaterialsDetailView(DetailView):
    model = Materials

materials/templates/materials/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
   <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Crimson+Text:400,400italic,600">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans+Condensed:700">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}" >
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"> 
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/estilos.css' %}">
   <!--  <script src="assets/js/querys.js"></script> -->
    <!-- Título do da página -->
    <title>Home | Museu</title>
  </head>
  <!-- Corpo da página -->
  <body>
    <!-- Cabeçalho -->
    <nav class="navbar navbar-dark p-0 flex-md-nowrap shadow" style="background-color: #1d4482;">
      <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#" style="visibility: hidden !important;">LojaHome</a>
      <input type="text" class="form-control form-control-primary w-75" placeholder="Procure por algo...">
     <a  href="/admin"><button type="button" class="btn btn-secondary botao-login" data-bs-target="#staticBackdrop"><i class="fas fa-user" style="margin-right: 10px;"></i>Meu Login</button></a>
     

    
     <!-- <button type="button" class="btn btn-secondary botao-login" data-bs-toggle="modal" data-bs-target="#staticBackdrop"><i class="fas fa-user" style="margin-right: 10px;"></i>Meu Login</button> -->

      <!-- Modal -->
      <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="staticBackdropLabel"><i class="fas fa-lock" style="color: #0f2241"></i> Painel Administrativo</h5>
              <i class="far fa-times-circle" data-bs-dismiss="modal" style="cursor: pointer; color: red; margin-top: 10px; font-size: 20px;"></i>
            </div>
            <div class="modal-body">
              <div class="mb-3">
                <label for="email" class="form-label"><strong>Email</strong></label>
                <input type="email" class="form-control" id="email" placeholder="Seu email">
              </div>
              <div class="mb-3">
                <label for="senha" class="form-label"><strong>Senha</strong></label>
                <input type="password" class="form-control" id="senha" placeholder="Sua senha">
              </div>
              <div class="mb-2 ml-1">
                <a href=""><p>Esqueceu a senha?</p></a>
              </div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-primary botao-logar"  style="color: #1d4482"><strong>Logar</strong></button>
            </div>
          </div>
        </div>
      </div>
    </nav>
    <section>
      <div class="s-layout">
        <!-- Sidebar -->
        <div class="s-layout__sidebar">
          <a class="s-sidebar__trigger" href="#0">
            <i class="fa fa-bars"></i>
          </a>
          <nav class="s-sidebar__nav">
            <img  src="{% static 'imagens/sidebar.png' %}" height="100%">
          <ul>
          <li style="margin-top: -35px;">
              <img src="{% static 'imagens/logo2.png' %}" width="100%" height="100%">
            
          </li>
       

          <li>
          <li>
            <a class="s-sidebar__nav-link " href="/">
              <i class="fa fa-home" style="margin-left: 10px;"></i><strong><em>Principal</em></strong>
             </a>
          </li>
          <li>
            <a class="s-sidebar__nav-link sidebar-selecionado" href="/artifacts">
              <i class="fas fa-list" style="margin-left: 10px;"></i><strong><em>Produtos</em></strong>
            </a>
          </li>
          <li>
           <a class="s-sidebar__nav-link" href="/collection/">
              <i class="fas fa-folder-open" style="margin-left: 10px;"></i><strong><em>Coleções</em></strong>
           </a>
          </li>
          <li>
            <a class="s-sidebar__nav-link" href="/materials/">
             <i class="fas fa-atlas" style="margin-left: 10px;"></i><strong><em>Materiais</em></strong>
            </a>
          </li>
          {% if user.is_authenticated %}

          <li>
            <a class="s-sidebar__nav-link" href="artifacts/add/">
             <i class="fas fa-atlas" style="margin-left: 10px;"></i><strong><em>Cadastrar Produtos (provisorio)</em></strong>
            </a>
          </li>
          {% endif %}
          </ul>
          </nav>
        </div>
     
   
      <!-- Content -->
      <main class="s-layout__content">

        {% block content %}  {% endblock %}
    
      </main>
    </div>
    </section>
  </body>
  <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/javascript.js' %}"></script>

</html>

materials/templates/materials/materials_detail.html
{% extends "artifacts/base.html" %}

<!-- {% block title %}{{ artifacts.title }}{% endblock %} -->

{% block content %}
<div>
    <h2>{{ artifacts.title }}</h2>
    <p class="date">
        Publicado em {{ artifacts.created }} por {{ artifacts.post_author }}
    </p>
    <p>Nome: {{ artifacts.name }}</p>
    <p>Código interno: {{ artifacts.slug }}</p>
    <p>Descrição: {{ artifacts.description}}</p>
    <p>Autor: {{ artifacts.author }}</p>
    <p>Sobre: {{ artifacts.about|safe }}</p>
    <p>Usabilidade: {{ artifacts.usage }}</p>
    <p>Estilo: {{ artifacts.style }}</p>
    <p>Cultura: {{ artifacts.culture }}</p>
    <p>Etnia: {{ artifacts.ethnicity }}</p>
    <p>Idade: {{ artifacts.age }}</p>
    <p>Inscrições: {{ artifacts.inscriptions }}</p>
    <p>Data de fabricação: {{ artifacts.fabrication_date }}</p>
    <p>Número do livro tombo: {{ artifacts.heritage_id }}</p>
    <p>Fabricação: {{ artifacts.manufacture }}</p>
    <p>Coleção: {{ artifacts.collection }}</p>
    <p>Constituido de: {{ artifacts.material }}</p>
    <p>Decoração: {{ artifacts.decoration }}</p>
    <p>Comprimento: {{ artifacts.length }}</p>
    <p>Largura: {{ artifacts.width }}</p>
    <p>Diâmetro: {{ artifacts.diameter }}</p>
    <p>Altura: {{ artifacts.height }}</p>
    <p>Circunferência: {{ artifacts.circumference }}</p>
    <p>Profundidade: {{ artifacts.depth }}</p>    
    <p>Peso: {{ artifacts.weight }}</p>
    <p>Proprietário: {{ artifacts.owner }}</p>
    <p>Data de aquisição: {{ artifacts.acqusition_date }}</p>
    <p>Doador: {{ artifacts.donor }}</p>
    <p>Último dono: {{artifacts.last_owner }}</p>
    <p>Caráter: {{ artifacts.personality }}</p>
    <p>Atualizado em: {{ artifacts.updated }}</p>
    <img src="{{ artifacts.image.url }}" alt="Image" height="30%" width="30%"/>
    <a href="/contact/">Requisição de empréstimo</a>
</div>
    
{% endblock %}

materials/templates/materials/materials_list.html
              {% extends "artifacts/base.html" %}
              {% load static %}
{% block title %} LojaParque Aquático {% endblock %}

{% block content %}

<section class = 'd-flex justify-content-center'>
  

  
  
      
<div class="row">


<div>
    <form method="post" action="addlogic">
      {% csrf_token %}
      <div class="col-9 search-div"></div>
      <input class="form-control" type="text" id="search" name="search" placeholder="Digite o nome do artefato para buscar..." >
    
  
    <li>Coleções Filtro</li>
     {% for collection in collection %}
     <li> <input type="checkbox" name="checks[]" value="{{ collection.id }}" id=checkbox />{{ collection.name }}</li>
{% endfor %}

      <input type="submit" name="btnsubmit" value="Filtrar">
     </form>
  
    </div>

   
    {% for artifacts in artifacts_list %}
    
  

    
        <div class="Card1"> 
          <div class="photo">
            <img src="{{ artifacts.image.url }}" heigh= "100px" width="200px"/>
          </div>
            <ul class="details">
              <h4> {{ artifacts.name }} </h4>
              <li>Autoria: {{ artifacts.author }}</li>
              <li>Ano: {{ artifacts.age }}</li>
              Coleção: {{ artifacts.collection}}
            </ul>  
            <div class="description">
              <div class="line">
                <h1 class="product_name" style="color: #3d498e !important">LojaParque Aquático</h1>
                <h1 class="product_price"></h1>
              </div>
              <h2>Descrição</h2>
              <p class="summary"> {{ artifacts.description|slice:"0:110" }}  </p>
          
              {% if user.is_authenticated %}
              <a  href="{{artifacts.get_main_edit}}"><button type="button" class="btn float-left botao-cadastrar" data-bs-toggle="modal" data-bs-target="#exampleModal" style="margin-top: -50px;"><i class="fas fa-plus"></i> Editar Artefato</button></a> 
          {% endif %}
         
              <a href="{{artifacts.get_absolute_url}}">Detalhes</a>

            </div>
          </div>
      
 




    {% endfor %}

    <div class="pagination">
      <span class="step-links">
        
          {% if artifacts_list.has_previous %}
              <a href="?page={{ artifacts_list.previous_page_number }}"><i class="fas fa-arrow-left"></i></a>
          {% endif %}
          
          {% if artifacts_list.paginator.num_pages %}
          <span class="current">
              {{ artifacts_list.number }} de {{ artifacts_list.paginator.num_pages }}
          </span>
          {% endif %}
      
          {% if artifacts_list.has_next %}
              <a href="?page={{ artifacts_list.next_page_number }}"><i class="fas fa-arrow-right"></i></a>
          {% endif %}
      </span>
    </div>

</div>

</section>




    {% endblock %}